[build]
  command = "npm run build"
  publish = "dist/word-game"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  SUPABASE_URL = "https://kzdvsokfiaqoyrchwowk.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZHZzb2tmaWFxb3lyY2h3b3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODYyNTgsImV4cCI6MjA2MTg2MjI1OH0.kVvwAhTHCHl186t7CVGxQt3SNPAPUBfKp_53trVUOWI"